#!/usr/bin/env python3
"""Create a pull request from a fork branch to the upstream repo.

Uses GitHub REST API directly — no gh CLI dependency.

Usage:
    python3 scripts/create_pr.py <upstream> <fork-owner> <branch> --title "..." --body "..."
    python3 scripts/create_pr.py opendatahub-io/odh-dashboard ederign epic/RHAISTRAT-1749-E001 \
        --title "RHAISTRAT-1749-E001: Add pipeline metrics" \
        --body "Generated by epic-codegen"
"""

import argparse
import json
import re
import sys

import github_utils


def _apply_template(body, template):
    """Append any PR template sections missing from the body."""
    template_headers = re.findall(r'^(##\s+.+)$', template, re.MULTILINE)

    for header in template_headers:
        if not re.search(re.escape(header), body, re.IGNORECASE):
            pattern = (re.escape(header)
                       + r'\n(.*?)(?=\n##\s|\Z)')
            match = re.search(pattern, template,
                              re.MULTILINE | re.DOTALL)
            if match:
                body += "\n\n" + match.group(0).rstrip()

    return body


def create_pr(upstream_slug, fork_owner, branch, title, body,
              base=None, token_var=None):
    """Create a pull request from fork to upstream.

    Fetches the target repo's PR template and appends any sections
    missing from the provided body.

    Args:
        upstream_slug: upstream owner/repo (e.g., "org/repo")
        fork_owner: fork owner username
        branch: branch name in the fork
        title: PR title
        body: PR body (markdown)
        base: target branch in upstream (default: repo's default branch)
        token_var: env var name for GitHub token

    Returns:
        dict with: number, url, html_url, state
    """
    token = github_utils.require_env(token_var)
    upstream_owner, upstream_repo = upstream_slug.split("/")

    if not base:
        repo_info = github_utils.get_repo(upstream_owner, upstream_repo, token)
        if not repo_info:
            raise ValueError(f"Upstream repo {upstream_slug} not found")
        base = repo_info["default_branch"]

    template = github_utils.get_pr_template(
        upstream_owner, upstream_repo, token)
    if template:
        body = _apply_template(body, template)

    pr = github_utils.create_pull_request(
        upstream_owner, upstream_repo,
        fork_owner, branch, base,
        title, body, token,
    )

    return {
        "number": pr["number"],
        "url": pr["url"],
        "html_url": pr["html_url"],
        "state": pr["state"],
        "base": base,
    }


def main():
    parser = argparse.ArgumentParser(
        description="Create PR from fork branch to upstream")
    parser.add_argument("upstream", help="Upstream owner/repo (e.g., org/repo)")
    parser.add_argument("fork_owner", help="Fork owner username")
    parser.add_argument("branch", help="Branch name in the fork")
    parser.add_argument("--title", required=True, help="PR title")
    parser.add_argument("--body", default="", help="PR body (markdown)")
    parser.add_argument("--base", default=None,
                        help="Target branch (default: repo's default branch)")
    parser.add_argument("--gh-token-var", default=None,
                        help="Env var for GitHub token")
    parser.add_argument("--json", action="store_true",
                        help="Output as JSON")
    args = parser.parse_args()

    try:
        result = create_pr(
            args.upstream,
            args.fork_owner,
            args.branch,
            args.title,
            args.body,
            base=args.base,
            token_var=args.gh_token_var,
        )

        if args.json:
            json.dump(result, sys.stdout, indent=2)
            print()
        else:
            print(f"PR #{result['number']}: {result['html_url']}")

        sys.exit(0)
    except (ValueError, EnvironmentError) as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
