#!/usr/bin/env python3
"""Generate an interactive pipeline story HTML for a strategy.

Reads pipeline artifacts (strategy.md, scores, diffs, reviews) and produces
a self-contained HTML dashboard showing the end-to-end Agentic SDLC flow.

Usage:
    python3 scripts/pipeline_story.py RHAISTRAT-1749 \\
        --data-dir /path/to/pipeline-data/RHAISTRAT-1749 \\
        --output-dir epic-reports
"""

import argparse
import html
import json
import os
import re
import sys
from datetime import datetime, timezone


def read_file(path):
    """Read file contents, return empty string if missing."""
    try:
        with open(path, "r") as f:
            return f.read()
    except FileNotFoundError:
        return ""


def read_json(path):
    """Read JSON file, return empty dict if missing."""
    try:
        with open(path, "r") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


def parse_strategy_sections(md_text):
    """Parse strategy.md into named sections by h2 headers."""
    sections = {}
    current_key = "_preamble"
    current_lines = []

    for line in md_text.splitlines():
        if line.startswith("## "):
            if current_lines:
                sections[current_key] = "\n".join(current_lines).strip()
            current_key = line[3:].strip()
            current_lines = []
        else:
            current_lines.append(line)

    if current_lines:
        sections[current_key] = "\n".join(current_lines).strip()

    return sections


def parse_subsections(text):
    """Split a section body by ### headers into ordered list of (title, content)."""
    subsections = []
    current_title = None
    current_lines = []
    for line in text.splitlines():
        if line.startswith("### "):
            if current_title is not None:
                subsections.append((current_title, "\n".join(current_lines).strip()))
            current_title = line[4:].strip()
            current_lines = []
        else:
            current_lines.append(line)
    if current_title is not None:
        subsections.append((current_title, "\n".join(current_lines).strip()))
    return subsections


def extract_title(md_text):
    """Extract h1 title from markdown."""
    for line in md_text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def extract_tldr(sections):
    """Extract TL;DR from the Strategy section."""
    strat = sections.get("Strategy (AI Generated by Agentic SDLC Pipeline)", "")
    in_tldr = False
    tldr_lines = []
    for line in strat.splitlines():
        if line.strip().startswith("### TL;DR"):
            in_tldr = True
            continue
        if in_tldr:
            if line.startswith("###") or line.startswith("## "):
                break
            tldr_lines.append(line)
    return "\n".join(tldr_lines).strip()


def extract_tables(sections):
    """Extract markdown tables from sections as list of dicts."""
    results = {}
    for key in ["Affected Components", "Impacted Teams"]:
        strat = sections.get("Strategy (AI Generated by Agentic SDLC Pipeline)", "")
        table_lines = []
        in_section = False
        for line in strat.splitlines():
            if f"### {key}" in line:
                in_section = True
                continue
            if in_section:
                if line.startswith("###") or line.startswith("## "):
                    break
                if "|" in line:
                    table_lines.append(line)

        if len(table_lines) >= 2:
            headers = [h.strip() for h in table_lines[0].split("|") if h.strip()]
            rows = []
            for tl in table_lines[2:]:
                cells = [c.strip() for c in tl.split("|") if c.strip()]
                if cells:
                    rows.append(cells)
            results[key] = {"headers": headers, "rows": rows}

    return results


def escape(text):
    """HTML-escape text."""
    return html.escape(str(text)) if text else ""


def md_inline_to_html(text):
    """Convert basic inline markdown (bold, italic, code) to HTML."""
    if not text:
        return ""
    t = html.escape(str(text))
    t = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', t)
    t = re.sub(r'\*(.+?)\*', r'<em>\1</em>', t)
    t = re.sub(r'`(.+?)`', r'<code class="text-blue-400 bg-slate-800 px-1 rounded text-xs">\1</code>', t)
    t = t.replace("\n", "<br>")
    return t


def md_to_html(text):
    """Convert markdown with headers, lists, paragraphs, and inline formatting to HTML."""
    if not text:
        return ""
    lines = text.strip().splitlines()
    html_parts = []
    in_list = False
    for line in lines:
        stripped = line.strip()
        if not stripped:
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            html_parts.append("")
            continue
        if stripped.startswith("### "):
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            html_parts.append(f'<h5 class="font-semibold text-slate-200 mt-4 mb-2">{md_inline_to_html(stripped[4:])}</h5>')
        elif stripped.startswith("- "):
            if not in_list:
                html_parts.append('<ul class="list-disc list-inside space-y-1 ml-2">')
                in_list = True
            html_parts.append(f'<li>{md_inline_to_html(stripped[2:])}</li>')
        else:
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            html_parts.append(f'<p class="mb-2">{md_inline_to_html(stripped)}</p>')
    if in_list:
        html_parts.append("</ul>")
    return "\n".join(html_parts)


def diff_to_html(patch_text):
    """Convert a unified diff to syntax-highlighted HTML."""
    if not patch_text:
        return '<p class="text-slate-500 italic">No diff available</p>'

    lines_html = []
    for line in patch_text.splitlines():
        escaped = escape(line)
        if line.startswith("+++") or line.startswith("---"):
            lines_html.append(
                f'<div class="text-slate-400 font-semibold">{escaped}</div>'
            )
        elif line.startswith("@@"):
            lines_html.append(
                f'<div class="text-purple-400 font-semibold bg-purple-900/20">{escaped}</div>'
            )
        elif line.startswith("+"):
            lines_html.append(
                f'<div class="text-emerald-400 bg-emerald-900/20">{escaped}</div>'
            )
        elif line.startswith("-"):
            lines_html.append(
                f'<div class="text-red-400 bg-red-900/20">{escaped}</div>'
            )
        elif line.startswith("diff "):
            lines_html.append(
                f'<div class="text-blue-400 font-bold mt-2">{escaped}</div>'
            )
        else:
            lines_html.append(f'<div class="text-slate-300">{escaped}</div>')

    return "\n".join(lines_html)


def md_table_to_html(table_data, extra_classes=""):
    """Render a parsed markdown table as HTML."""
    if not table_data:
        return ""
    headers = table_data["headers"]
    rows = table_data["rows"]

    th = "".join(
        f'<th class="px-4 py-3 text-left text-xs font-semibold text-slate-400 uppercase tracking-wider">{escape(h)}</th>'
        for h in headers
    )
    body = ""
    for row in rows:
        cells = "".join(
            f'<td class="px-4 py-3 text-sm text-slate-300 border-t border-slate-700/50">{escape(c)}</td>'
            for c in row
        )
        body += f"<tr>{cells}</tr>"

    return f"""
    <div class="overflow-x-auto {extra_classes}">
      <table class="w-full">
        <thead><tr class="border-b border-slate-700">{th}</tr></thead>
        <tbody>{body}</tbody>
      </table>
    </div>"""


def generate_pipeline_story(strat_key, data_dir, output_dir="epic-reports",
                            screenshots_dir=None):
    """Generate pipeline story HTML for a strategy."""
    os.makedirs(output_dir, exist_ok=True)

    strategy_md = read_file(os.path.join(data_dir, "strategy.md"))
    summary_json = read_json(os.path.join(data_dir, "strategy-summary.json"))
    run_log_text = read_file(os.path.join(data_dir, "run-log.jsonl"))

    run_log_entries = []
    for line in run_log_text.strip().splitlines():
        line = line.strip()
        if line:
            try:
                run_log_entries.append(json.loads(line))
            except json.JSONDecodeError:
                pass

    sections = parse_strategy_sections(strategy_md)
    title = extract_title(strategy_md)
    tldr = extract_tldr(sections)
    tables = extract_tables(sections)

    epics = summary_json.get("epics", [])
    epic_with_pr = None
    for ep in epics:
        if ep.get("pr_url"):
            epic_with_pr = ep
            break

    # Load epic titles, dependencies, and blocks
    epic_titles = {}
    epic_deps = {}
    epic_blocks = {}
    jira_epics = read_json(os.path.join(data_dir, "jira-epics.json"))
    if isinstance(jira_epics, list) and jira_epics:
        for je in jira_epics:
            eid = je["epic_id"]
            epic_titles[eid] = je.get("title", "")
            epic_deps[eid] = je.get("dependencies") or []
            epic_blocks[eid] = je.get("blocks") or []
    else:
        for ep in epics:
            eid = ep["epic_id"]
            task_md = read_file(os.path.join(data_dir, eid, "epic-task.md"))
            meta_yaml = read_file(os.path.join(data_dir, eid, "run-metadata.yaml"))
            for line in task_md.splitlines():
                if line.startswith("title:"):
                    epic_titles[eid] = line.split(":", 1)[1].strip()
            blocked_by = []
            in_blocked = False
            for line in meta_yaml.splitlines():
                if line.startswith("blocked_by:"):
                    in_blocked = True
                    continue
                if in_blocked:
                    if line.startswith("- "):
                        blocked_by.append(line.strip().lstrip("- "))
                    else:
                        in_blocked = False
            epic_deps[eid] = blocked_by
            for dep in blocked_by:
                epic_blocks.setdefault(dep, []).append(eid)

    all_epic_data = {}
    for ep in epics:
        eid = ep["epic_id"]
        epic_dir = os.path.join(data_dir, eid)
        has_artifacts = os.path.exists(os.path.join(epic_dir, "v1"))
        all_epic_data[eid] = {
            "has_artifacts": has_artifacts,
            "spec": read_file(os.path.join(epic_dir, "codegen-spec.md")),
            "plan": read_file(os.path.join(epic_dir, "codegen-plan.md")),
            "task": read_file(os.path.join(epic_dir, "epic-task.md")),
            "metadata": read_file(os.path.join(epic_dir, "run-metadata.yaml")),
            "pr_replies": read_json(os.path.join(epic_dir, "pr-replies.json")),
            "v1_scores": read_json(os.path.join(epic_dir, "v1", "scores.json")),
            "v1_diff": read_file(os.path.join(epic_dir, "v1", "diff.patch")),
            "v2_feedback": read_file(
                os.path.join(epic_dir, "v2", "review-feedback.md")
            ),
            "v2_sanity": read_file(
                os.path.join(epic_dir, "v2", "sanity-check.md")
            ),
        }

    epic_data = all_epic_data.get(
        epic_with_pr["epic_id"], {}
    ) if epic_with_pr else {}

    screenshots_base = screenshots_dir or os.path.join(output_dir, "screenshots")

    rfe_summary = sections.get("Summary", "")
    customers_raw = sections.get("Affected Customers", "")
    customers = re.sub(
        r'\*\*[A-Z][A-Za-z\s&\.\'-]+\*\*(?=\s+and other)',
        '**[Customer]**',
        customers_raw,
    )
    customers = customers.replace("wx.ai", "[partner product]")
    biz_justification = sections.get("Business Justification", "").replace("wx.ai", "[partner product]")
    acceptance = sections.get("Acceptance Criteria", "")
    staff_engineer = sections.get("Staff Engineer / SME Input", "")
    staff_engineer_tags = ""
    for line in staff_engineer.splitlines():
        if line.startswith("### "):
            tag_text = escape(line[4:].strip())
            staff_engineer_tags += f'<span class="px-2 py-1 rounded-md bg-slate-700/50 text-slate-300 text-xs">{tag_text}</span>\n'

    rfe_sections = [
        ("Summary", rfe_summary),
        ("Affected Customers", customers),
        ("Business Justification", biz_justification),
        ("Acceptance Criteria", acceptance),
    ]
    rfe_tree_html = ""
    for sec_title, sec_content in rfe_sections:
        if not sec_content.strip():
            continue
        rfe_tree_html += f"""
        <details class="group/sub mb-1">
          <summary class="cursor-pointer text-xs font-semibold text-slate-400 hover:text-slate-200 flex items-center gap-1 py-1">
            <svg class="w-3 h-3 transition-transform group-open/sub:rotate-90" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
            {escape(sec_title)}
          </summary>
          <div class="ml-4 mt-1 mb-2 text-slate-300 text-sm leading-relaxed border-l-2 border-slate-700/50 pl-3">{md_to_html(sec_content)}</div>
        </details>"""

    strat_body = sections.get("Strategy (AI Generated by Agentic SDLC Pipeline)", "")
    strat_subsections = parse_subsections(strat_body)
    strat_tree_html = ""
    for sub_title, sub_content in strat_subsections:
        if sub_title == "TL;DR":
            continue
        strat_tree_html += f"""
        <details class="group/sub mb-1">
          <summary class="cursor-pointer text-xs font-semibold text-slate-400 hover:text-slate-200 flex items-center gap-1 py-1">
            <svg class="w-3 h-3 transition-transform group-open/sub:rotate-90" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
            {escape(sub_title)}
          </summary>
          <div class="ml-4 mt-1 mb-2 text-slate-300 text-sm leading-relaxed border-l-2 border-slate-700/50 pl-3">{md_to_html(sub_content)}</div>
        </details>"""

    scores = epic_data.get("v1_scores", {})
    dims = scores.get("dimensions", {})
    weighted_avg = scores.get("weighted_average", 0)
    verdict = scores.get("verdict", "")

    pr_replies = epic_data.get("pr_replies", {}).get("replies", [])

    # Build vertical DAG HTML
    epic_status_map = {ep["epic_id"]: ep.get("status", "") for ep in epics}

    def dag_node_html(eid):
        status = epic_status_map.get(eid, "")
        short_id = eid.split("-")[-1]
        ep_title = epic_titles.get(eid, "")
        short_title = ep_title[:30] + "..." if len(ep_title) > 30 else ep_title
        if status == "PRCreated":
            node_bg = "bg-blue-900/40 border-blue-600/60"
            node_text = "text-blue-300"
            dot_color = "bg-blue-500"
            status_label = "PR Created"
        elif status in ("Done", "Closed"):
            node_bg = "bg-emerald-900/40 border-emerald-600/60"
            node_text = "text-emerald-300"
            dot_color = "bg-emerald-500"
            status_label = "Done"
        else:
            node_bg = "bg-red-900/30 border-red-700/40"
            node_text = "text-red-300"
            dot_color = "bg-red-500"
            status_label = "Blocked"
        return f"""<div class="arch-node {node_bg} border rounded-lg px-4 py-3 text-center min-w-[160px]">
            <p class="font-mono text-xs font-bold {node_text}">{escape(short_id)}</p>
            <p class="text-[10px] text-slate-400 mt-1 leading-tight">{escape(short_title)}</p>
            <div class="flex items-center justify-center gap-1.5 mt-2">
              <span class="w-1.5 h-1.5 rounded-full {dot_color}"></span>
              <span class="text-[10px] text-slate-500">{escape(status_label)}</span>
            </div>
          </div>"""

    down_arrow = """<div class="flex justify-center py-1">
        <svg class="w-5 h-5 text-slate-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 14l-7 7-7-7"/>
        </svg>
      </div>"""

    fork_connector = """<div class="flex justify-center py-1">
        <svg class="w-5 h-5 text-slate-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 14l-7 7-7-7"/>
        </svg>
      </div>"""

    # Build DAG by topological layers
    roots = [eid for eid in [ep["epic_id"] for ep in epics] if not epic_deps.get(eid)]
    visited = set()
    layers = []

    def build_layers(current_layer):
        if not current_layer:
            return
        layers.append(current_layer)
        visited.update(current_layer)
        next_layer = []
        for eid in current_layer:
            for child in epic_blocks.get(eid, []):
                if child not in visited and child in epic_status_map:
                    all_deps_visited = all(d in visited for d in epic_deps.get(child, []))
                    if all_deps_visited and child not in next_layer:
                        next_layer.append(child)
        build_layers(next_layer)

    build_layers(roots)

    dep_graph_dag = '<div class="flex flex-col items-center gap-0">'
    for li, layer in enumerate(layers):
        if li > 0:
            dep_graph_dag += fork_connector
        if len(layer) == 1:
            dep_graph_dag += dag_node_html(layer[0])
        else:
            dep_graph_dag += '<div class="flex items-start gap-6 justify-center">'
            for eid in layer:
                dep_graph_dag += dag_node_html(eid)
            dep_graph_dag += '</div>'
    dep_graph_dag += '</div>'

    # Build score bars HTML
    score_bars = ""
    for dim_name, dim_data in dims.items():
        score_val = dim_data.get("score", 0)
        weight = dim_data.get("weight", 0)
        pct = score_val * 10
        color = "bg-emerald-500" if score_val >= 8 else ("bg-amber-500" if score_val >= 6 else "bg-red-500")
        score_bars += f"""
        <div class="flex items-center gap-3 mb-2">
          <span class="w-24 text-sm font-medium text-slate-300 capitalize">{escape(dim_name)}</span>
          <span class="w-10 text-xs text-slate-500 text-right">{int(weight*100)}%</span>
          <div class="flex-1 h-5 bg-slate-700 rounded-full overflow-hidden">
            <div class="{color} h-full rounded-full transition-all duration-1000" style="width: {pct}%"></div>
          </div>
          <span class="w-12 text-sm font-bold text-slate-200 text-right">{score_val}/10</span>
        </div>"""

    epic_cards_html = ""
    for ep in epics:
        eid = ep["epic_id"]
        status = ep.get("status", "Unknown")
        repo = ep.get("target_repo", "")
        ep_title = epic_titles.get(eid, "")
        badge_color = "bg-blue-500/20 text-blue-400" if status == "PRCreated" else "bg-red-500/20 text-red-400"
        pr_link = ""
        if ep.get("pr_url"):
            pr_link = f'<a href="{escape(ep["pr_url"])}" target="_blank" class="text-blue-400 hover:text-blue-300 text-xs">View PR &rarr;</a>'

        epic_cards_html += f"""
        <div class="bg-slate-800/50 border border-slate-700/50 rounded-lg p-4">
          <div class="flex items-center justify-between mb-2">
            <a href="https://redhat.atlassian.net/browse/{escape(eid)}" target="_blank"
               class="font-mono text-sm font-bold text-blue-400 hover:text-blue-300">{escape(eid)}</a>
            <span class="px-2 py-0.5 rounded text-xs font-semibold {badge_color}">{escape(status)}</span>
          </div>
          <p class="text-sm text-slate-300 mb-1">{escape(ep_title)}</p>
          <p class="text-xs text-slate-500 font-mono mb-1">{escape(repo)}</p>
          {pr_link}
        </div>"""

    # PR conversation HTML
    pr_convo_html = ""
    if pr_replies:
        for reply in pr_replies:
            user = reply.get("user", "Unknown")
            body = reply.get("reply_body", "")
            action = reply.get("action", "")
            ts = reply.get("timestamp", "")
            pr_convo_html += f"""
            <div class="flex gap-3 mb-3">
              <div class="w-8 h-8 rounded-full bg-slate-700 flex items-center justify-center text-xs font-bold text-slate-300 shrink-0">
                {escape(user[0:2])}
              </div>
              <div class="flex-1 bg-slate-800/50 rounded-lg p-3 border border-slate-700/50">
                <div class="flex items-center gap-2 mb-1">
                  <span class="text-sm font-semibold text-slate-300">{escape(user)}</span>
                  <span class="px-1.5 py-0.5 rounded text-xs bg-amber-500/20 text-amber-400">{escape(action)}</span>
                  <span class="text-xs text-slate-500">{escape(ts)}</span>
                </div>
                <p class="text-sm text-slate-400">{escape(body)}</p>
              </div>
            </div>"""
    else:
        pr_convo_html = '<p class="text-slate-500 italic text-sm">PR conversation data will appear here after re-run</p>'

    # Diff HTML
    v1_diff_html = diff_to_html(epic_data.get("v1_diff", ""))

    # Tables
    components_table = md_table_to_html(tables.get("Affected Components"))
    teams_table = md_table_to_html(tables.get("Impacted Teams"))

    # Screenshot helper
    def screenshot_slot(name, label):
        img_path = os.path.join(screenshots_base, f"{name}.png")
        if os.path.exists(img_path):
            rel = os.path.relpath(img_path, output_dir)
            return f'<img src="{escape(rel)}" alt="{escape(label)}" class="rounded-lg border border-slate-700 max-w-[50%]" />'
        return f"""
        <div class="border-2 border-dashed border-slate-600 rounded-lg p-8 text-center">
          <svg class="w-12 h-12 mx-auto mb-3 text-slate-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
                  d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"/>
          </svg>
          <p class="text-slate-500 text-sm font-medium">{escape(label)}</p>
          <p class="text-slate-600 text-xs mt-1">screenshots/{escape(name)}.png</p>
        </div>"""

    pr_url = ""
    if epic_with_pr:
        pr_url = epic_with_pr.get("pr_url", "")
    epic_id_display = epic_with_pr["epic_id"] if epic_with_pr else "N/A"

    # Build per-run timeline from run-log.jsonl
    epic_summary_by_id = {ep["epic_id"]: ep for ep in epics}

    STATUS_LABELS = {
        "PRCreated": "PR Opened",
        "ReviewPending": "Code Generated",
        "Blocked": "Blocked",
        "Done": "Done",
        "InProgress": "In Progress",
        "Failed": "Failed",
    }

    def friendly_status(raw):
        return STATUS_LABELS.get(raw, raw)

    def build_run_timeline_blocks():
        """Build collapsible timeline blocks grouped by pipeline run."""
        if not run_log_entries:
            return '<p class="text-slate-500 italic text-sm">No pipeline runs recorded yet.</p>'

        blocks = ""
        for run_idx, run in enumerate(run_log_entries):
            ts_raw = run.get("timestamp", "")
            ts_display = ts_raw[:19].replace("T", " ") + " UTC" if ts_raw else "Unknown"
            actions = run.get("actions", [])
            processed = run.get("epics_processed", 0)
            blocked = run.get("epics_blocked", 0)

            processed_actions = [a for a in actions if a.get("to") not in ("Blocked",)]
            blocked_epics = [
                eid for eid, ep in epic_summary_by_id.items()
                if ep.get("status") == "Blocked"
            ]

            is_open = "open" if run_idx == len(run_log_entries) - 1 else ""

            run_content = ""
            for action in processed_actions:
                eid = action.get("epic", "")
                from_state = action.get("from", "")
                to_state = action.get("to", "")
                version = action.get("version", 1)
                ep_info = epic_summary_by_id.get(eid, {})
                edata = all_epic_data.get(eid, {})
                ep_title = epic_titles.get(eid, "")
                repo = ep_info.get("target_repo", "")
                ep_pr_url = ep_info.get("pr_url", "") or ""
                pr_num = ep_pr_url.split("/")[-1] if ep_pr_url else ""

                e_scores = edata.get("v1_scores", {})
                e_dims = e_scores.get("dimensions", {})
                e_weighted = e_scores.get("weighted_average", 0)
                e_verdict = e_scores.get("verdict", "")

                e_score_bars = ""
                for dim_name, dim_data in e_dims.items():
                    sv = dim_data.get("score", 0)
                    w = dim_data.get("weight", 0)
                    pct = sv * 10
                    c = "bg-emerald-500" if sv >= 8 else ("bg-amber-500" if sv >= 6 else "bg-red-500")
                    e_score_bars += f"""
                    <div class="flex items-center gap-3 mb-2">
                      <span class="w-24 text-sm font-medium text-slate-300 capitalize">{escape(dim_name)}</span>
                      <span class="w-10 text-xs text-slate-500 text-right">{int(w*100)}%</span>
                      <div class="flex-1 h-5 bg-slate-700 rounded-full overflow-hidden">
                        <div class="{c} h-full rounded-full transition-all duration-1000" style="width: {pct}%"></div>
                      </div>
                      <span class="w-12 text-sm font-bold text-slate-200 text-right">{sv}/10</span>
                    </div>"""

                verdict_class = "bg-emerald-500/20 text-emerald-400" if e_verdict == "pass" else "bg-red-500/20 text-red-400"
                e_diff_html = diff_to_html(edata.get("v1_diff", ""))

                pr_button = ""
                if ep_pr_url:
                    pr_button = f'<a href="{escape(ep_pr_url)}" target="_blank" class="inline-flex items-center gap-2 mt-3 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white text-sm font-semibold rounded-lg transition-colors"><svg class="w-4 h-4" fill="currentColor" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>View PR on GitHub</a>'

                run_content += f"""
              <div class="bg-slate-800/50 border border-emerald-700/30 rounded-lg p-4 mb-3">
                <div class="flex items-center gap-2 mb-3">
                  <svg class="w-5 h-5 text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
                  </svg>
                  <a href="https://redhat.atlassian.net/browse/{escape(eid)}" target="_blank"
                     class="font-mono text-sm font-bold text-blue-400 hover:text-blue-300">{escape(eid)}</a>
                  <span class="px-2 py-0.5 rounded text-xs font-semibold bg-emerald-500/20 text-emerald-400">{escape(friendly_status(to_state))}</span>
                  <span class="text-xs text-slate-500">v{version}</span>
                </div>
                <p class="text-sm text-slate-300 mb-1">{escape(ep_title)}</p>
                <p class="text-xs text-slate-500 font-mono mb-3">{escape(repo)}</p>

                {f"""
                <div class="border-t border-slate-700 pt-3 mt-2">
                  <h6 class="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">Review Scores</h6>
                  {e_score_bars}
                  <div class="mt-2 pt-2 border-t border-slate-700 flex items-center justify-between">
                    <span class="text-sm font-medium text-slate-400">Weighted Average</span>
                    <div class="flex items-center gap-2">
                      <span class="text-xl font-bold text-emerald-400">{e_weighted}</span>
                      <span class="text-sm text-slate-500">/ 10</span>
                      <span class="px-2 py-0.5 rounded text-xs font-semibold {verdict_class}">{escape(e_verdict.upper()) if e_verdict else 'N/A'}</span>
                    </div>
                  </div>
                </div>
                """ if e_dims else ""}

                {f"""
                <details class="mt-3">
                  <summary class="cursor-pointer text-sm font-semibold text-slate-400 hover:text-slate-200 flex items-center gap-2">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"/></svg>
                    View generated diff
                  </summary>
                  <div class="mt-3 bg-slate-950 border border-slate-800 rounded-lg p-4 font-mono text-xs overflow-x-auto max-h-[400px] overflow-y-auto">
                    {e_diff_html}
                  </div>
                </details>
                """ if e_diff_html.strip() else ""}

                {f'<p class="mt-3 text-sm text-emerald-400 font-semibold">&rarr; Code v{version} <span class="text-slate-500 font-normal">(full epic code gen loop: spec &rarr; code &rarr; review &rarr; score)</span> &mdash; PR #{escape(pr_num)} opened</p>' if pr_num else ""}
                {pr_button}
              </div>"""

            if blocked_epics:
                run_content += """
              <div class="mt-2">
                <h6 class="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                  <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"/>
                  </svg>
                  Blocked Epics
                </h6>
                <div class="grid gap-2">"""
                for beid in blocked_epics:
                    btitle = epic_titles.get(beid, "")
                    brepo = epic_summary_by_id.get(beid, {}).get("target_repo", "")
                    blockers = epic_deps.get(beid, [])
                    blockers_text = ", ".join(
                        f'<span class="font-mono text-blue-400">{escape(b)}</span>'
                        for b in blockers
                    ) if blockers else "upstream epics"
                    run_content += f"""
                  <div class="bg-slate-800/30 border border-slate-700/30 rounded-lg p-3 flex items-center gap-3">
                    <svg class="w-4 h-4 text-slate-600 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"/>
                    </svg>
                    <div class="flex-1">
                      <div class="flex items-center gap-2">
                        <a href="https://redhat.atlassian.net/browse/{escape(beid)}" target="_blank"
                           class="font-mono text-xs font-bold text-slate-400 hover:text-blue-300">{escape(beid)}</a>
                        <span class="px-1.5 py-0.5 rounded text-[10px] font-semibold bg-red-500/20 text-red-400">BLOCKED</span>
                      </div>
                      <p class="text-xs text-slate-500 mt-0.5">{escape(btitle)}</p>
                    </div>
                    <div class="text-right">
                      <p class="text-[10px] text-slate-600">blocked by {blockers_text}</p>
                      <p class="text-[10px] text-slate-600 font-mono">{escape(brepo)}</p>
                    </div>
                  </div>"""
                run_content += """
                </div>
              </div>"""

            blocks += f"""
        <details class="bg-slate-800/30 border border-slate-700/50 rounded-xl overflow-hidden" {is_open}>
          <summary class="flex items-center gap-3 px-5 py-4 cursor-pointer hover:bg-slate-800/50 transition-colors">
            <div class="w-10 h-10 rounded-full bg-blue-900 border-2 border-blue-500 flex items-center justify-center">
              <span class="text-sm font-bold text-blue-400">{run_idx + 1}</span>
            </div>
            <div class="flex-1">
              <div class="flex items-center gap-2">
                <span class="text-sm font-bold text-white">Agentic Pipeline Loop {run_idx + 1}</span>
                <span class="px-2 py-0.5 rounded text-xs font-semibold bg-emerald-500/20 text-emerald-400">{processed} processed</span>
                {"" if not blocked else f'<span class="px-2 py-0.5 rounded text-xs font-semibold bg-red-500/20 text-red-400">{blocked} blocked</span>'}
              </div>
              <p class="text-xs text-slate-500 mt-0.5">{escape(ts_display)}</p>
            </div>
            <svg class="w-5 h-5 text-slate-500 shrink-0 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/></svg>
          </summary>
          <div class="px-5 pb-5 pt-2">
            {run_content}
          </div>
        </details>"""

            has_prs = any(
                a.get("to") == "PRCreated" for a in actions
            )
            is_last_run = run_idx == len(run_log_entries) - 1
            if has_prs and is_last_run:
                review_screenshot = ""
                screenshot_path = os.path.join(
                    screenshots_base, "copilot-review.png"
                )
                if os.path.exists(screenshot_path):
                    rel = os.path.relpath(screenshot_path, output_dir)
                    review_screenshot = f'<div class="flex justify-center mt-3"><img src="{escape(rel)}" alt="AI agent reviewing the PR" class="rounded-lg border border-purple-700/30 max-w-[50%]" /></div>'

                pr_epic_ids = [
                    a.get("epic", "") for a in actions
                    if a.get("to") == "PRCreated"
                ]
                pr_links = ""
                for peid in pr_epic_ids:
                    purl = epic_summary_by_id.get(peid, {}).get("pr_url", "")
                    if purl:
                        pr_links += f' <a href="{escape(purl)}" target="_blank" class="font-mono text-xs text-purple-400 hover:text-purple-300">{escape(peid)}</a>'

                blocks += f"""
        <details class="bg-purple-900/10 border border-purple-700/30 rounded-xl my-3 border-dashed overflow-hidden" open>
          <summary class="flex items-center gap-3 px-5 py-4 cursor-pointer hover:bg-purple-900/20 transition-colors">
            <div class="w-10 h-10 rounded-full bg-purple-900/50 border-2 border-purple-500/50 flex items-center justify-center">
              <svg class="w-5 h-5 text-purple-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/>
              </svg>
            </div>
            <div class="flex-1">
              <div class="flex items-center gap-2">
                <span class="text-sm font-bold text-purple-300">External Review</span>
                <span class="px-2 py-0.5 rounded text-xs font-semibold bg-purple-500/20 text-purple-400">OUTER LOOP</span>
              </div>
              <p class="text-xs text-slate-500 mt-0.5">AI agents and humans review PRs outside the pipeline — feedback is picked up on the next loop</p>
            </div>
            <svg class="w-5 h-5 text-slate-500 shrink-0 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/></svg>
          </summary>
          <div class="px-5 pb-5">
            <div class="bg-slate-900/50 border border-purple-700/20 rounded-lg p-4">
              <p class="text-sm text-slate-400 mb-2">Open PRs from Loop {run_idx + 1} are being reviewed by external AI agents (<span class="text-purple-300 font-semibold">GitHub Copilot</span>, <span class="text-purple-300 font-semibold">CodeRabbit</span>) and human engineers.{pr_links}</p>
              {review_screenshot}
              <p class="text-xs text-slate-500 mt-3 italic">The pipeline will pick up review feedback and act on it in the next agentic loop.</p>
            </div>
          </div>
        </details>"""

        return blocks

    epic_timeline_blocks = build_run_timeline_blocks()

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    page_html = f"""<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Agentic SDLC Pipeline Journey &mdash; {escape(strat_key)}</title>
<script src="https://cdn.tailwindcss.com"></script>
<script>
tailwind.config = {{
  theme: {{
    extend: {{
      fontFamily: {{
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['JetBrains Mono', 'SF Mono', 'Consolas', 'monospace'],
      }},
    }},
  }},
}}
</script>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600&display=swap');

  .stage-card {{
    transition: all 0.3s ease;
    cursor: pointer;
  }}
  .stage-card:hover {{
    transform: translateY(-2px);
  }}
  .stage-card.active {{
    ring: 2px;
    border-color: #3b82f6;
    box-shadow: 0 0 20px rgba(59, 130, 246, 0.2);
  }}

  .detail-panel {{
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.5s ease, opacity 0.3s ease;
    opacity: 0;
  }}
  .detail-panel.open {{
    max-height: 5000px;
    opacity: 1;
  }}

  .connector {{
    position: relative;
  }}
  .connector::after {{
    content: '';
    position: absolute;
    top: 50%;
    right: -24px;
    width: 24px;
    height: 2px;
    background: linear-gradient(90deg, #475569, #3b82f6);
  }}
  .connector:last-child::after {{
    display: none;
  }}

  .loop-arrow {{
    animation: pulse-loop 2s ease-in-out infinite;
  }}
  @keyframes pulse-loop {{
    0%, 100% {{ opacity: 0.5; }}
    50% {{ opacity: 1; }}
  }}

  .score-fill {{
    animation: fill-bar 1.5s ease-out forwards;
    width: 0%;
  }}
  .score-fill.animated {{
    width: var(--target-width);
  }}

  .arch-node {{
    transition: transform 0.2s ease, box-shadow 0.2s ease;
  }}
  .arch-node:hover {{
    transform: scale(1.05);
    box-shadow: 0 0 15px rgba(255,255,255,0.1);
  }}

  .pipeline-arrow {{
    color: #475569;
    font-size: 1.5rem;
    line-height: 1;
  }}
</style>
</head>
<body class="bg-slate-950 text-slate-200 min-h-screen">

<!-- ═══════════════ HERO HEADER ═══════════════ -->
<header class="relative overflow-hidden border-b border-slate-800">
  <div class="absolute inset-0 bg-gradient-to-br from-blue-950/40 via-slate-950 to-emerald-950/20"></div>
  <div class="relative max-w-7xl mx-auto px-6 py-8">
    <div class="flex items-center gap-3 mb-2">
      <div class="w-8 h-8 bg-red-600 rounded-sm flex items-center justify-center">
        <svg viewBox="0 0 24 24" class="w-5 h-5 text-white" fill="currentColor">
          <path d="M12 2L2 7v10l10 5 10-5V7L12 2zm0 2.18L19.18 8 12 11.82 4.82 8 12 4.18z"/>
        </svg>
      </div>
      <span class="text-sm font-semibold text-red-400 tracking-wider uppercase">Red Hat AI</span>
    </div>
    <h1 class="text-3xl md:text-4xl font-bold text-white mb-2">
      Agentic SDLC Pipeline Journey
    </h1>
    <p class="text-slate-400 text-lg">
      <a href="https://redhat.atlassian.net/browse/{escape(strat_key)}" target="_blank"
         class="text-blue-400 hover:text-blue-300 font-mono font-semibold">{escape(strat_key)}</a>
      &mdash; {escape(title.split(']')[-1].strip() if ']' in title else title)}
    </p>
    <p class="text-slate-500 text-sm mt-1">Generated {escape(timestamp)}</p>
  </div>
</header>

<!-- ═══════════════ ARCHITECTURE OVERVIEW ═══════════════ -->
<section class="max-w-7xl mx-auto px-6 py-8">
  <h2 class="text-lg font-semibold text-slate-300 mb-6 flex items-center gap-2">
    <svg class="w-5 h-5 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 17V7m0 10a2 2 0 01-2 2H5a2 2 0 01-2-2V7a2 2 0 012-2h2a2 2 0 012 2m0 10a2 2 0 002 2h2a2 2 0 002-2M9 7a2 2 0 012-2h2a2 2 0 012 2m0 10V7"/>
    </svg>
    Full Pipeline Architecture
  </h2>

  <div class="bg-slate-900/50 border border-slate-800 rounded-xl p-6 overflow-x-auto">
    <div class="flex items-center gap-4 min-w-[900px] justify-center">

      <!-- Human in the loop -->
      <div class="flex flex-col items-center gap-1 self-center">
        <svg class="w-7 h-7 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"/>
        </svg>
        <span class="text-[9px] text-slate-500 font-medium leading-tight text-center">PM or<br>Customer</span>
      </div>

      <span class="pipeline-arrow self-center">&rsaquo;</span>

      <!-- RFE Creator -->
      <div class="border-2 border-emerald-700/60 bg-emerald-900/20 rounded-xl p-4 flex flex-col gap-2 self-center min-w-[160px]">
        <p class="font-bold text-emerald-300 text-sm text-center mb-1">RFE Creator</p>
        <div class="flex flex-col gap-2">
          <div class="arch-node bg-emerald-900/40 border border-emerald-700/60 rounded-lg px-2 py-1.5 text-center">
            <p class="font-medium text-emerald-300 text-[10px]">Assess RFE</p>
          </div>
          <div class="arch-node bg-emerald-900/40 border border-emerald-700/60 rounded-lg px-2 py-1.5 text-center">
            <p class="font-medium text-emerald-300 text-[10px]">RFE Splitter</p>
          </div>
          <div class="arch-node bg-emerald-900/40 border border-emerald-700/60 rounded-lg px-2 py-1.5 text-center">
            <p class="font-medium text-emerald-300 text-[10px]">RFE Auto-Fix</p>
          </div>
        </div>
      </div>

      <span class="pipeline-arrow self-center">&rsaquo;</span>

      <!-- Strategy Group — Strat Creator as container -->
      <div class="border-2 border-emerald-700/60 bg-emerald-900/20 rounded-xl p-4 flex flex-col gap-2">
        <p class="font-bold text-emerald-300 text-sm text-center mb-1">Strat Creator</p>
        <div class="grid grid-cols-2 gap-2">
          <div class="arch-node bg-emerald-900/40 border border-emerald-700/60 rounded-lg px-2 py-1.5 text-center min-w-0">
            <p class="font-medium text-emerald-300 text-[10px]">Test Planner</p>
          </div>
          <div class="arch-node bg-rose-900/40 border border-rose-700/60 rounded-lg px-2 py-1.5 text-center min-w-0">
            <p class="font-medium text-rose-300 text-[10px]">Security Review</p>
          </div>
          <div class="arch-node bg-blue-900/40 border border-blue-700/60 rounded-lg px-2 py-1.5 text-center min-w-0">
            <p class="font-medium text-blue-300 text-[10px]">UI Prototype Gen</p>
          </div>
          <div class="arch-node bg-blue-900/40 border border-blue-700/60 rounded-lg px-2 py-1.5 text-center min-w-0">
            <p class="font-medium text-blue-300 text-[10px]">Component Onboarding</p>
          </div>
          <div class="arch-node bg-blue-900/40 border border-blue-700/60 rounded-lg px-2 py-1.5 text-center min-w-0">
            <p class="font-medium text-blue-300 text-[10px]">License Scanning</p>
          </div>
          <div class="arch-node bg-blue-900/40 border border-blue-700/60 rounded-lg px-2 py-1.5 text-center min-w-0">
            <p class="font-medium text-blue-300 text-[10px]">Accelerator Support</p>
          </div>
        </div>
      </div>

      <span class="pipeline-arrow self-center">&rsaquo;</span>

      <!-- Human in the loop -->
      <div class="flex flex-col items-center gap-1 self-center">
        <svg class="w-7 h-7 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"/>
        </svg>
        <span class="text-[9px] text-slate-500 font-medium leading-tight text-center">Staff/SME<br>Review</span>
      </div>

      <span class="pipeline-arrow self-center">&rsaquo;</span>

      <!-- Epic Decomposer -->
      <div class="border-2 border-amber-700/60 bg-amber-900/20 rounded-xl p-4 flex flex-col gap-2">
        <p class="font-bold text-amber-300 text-sm text-center mb-1">Epic Decomposer</p>
        <div class="arch-node bg-rose-900/40 border border-rose-700/60 rounded-lg px-3 py-1.5 text-center">
          <p class="font-medium text-rose-300 text-xs">Research Spikes</p>
        </div>
      </div>

      <span class="pipeline-arrow self-center">&rsaquo;</span>

      <!-- GATE -->
      <div class="flex flex-col items-center self-stretch">
        <span class="text-[10px] font-semibold text-slate-500 uppercase tracking-widest">Gate</span>
        <div class="arch-node bg-amber-900/40 border border-amber-700/60 rounded-lg px-3 py-1 text-center">
          <p class="font-medium text-amber-300 text-xs">Release Planner</p>
        </div>
        <div class="flex-1 border-l-2 border-dashed border-amber-600/50 mt-1"></div>
      </div>

      <span class="pipeline-arrow self-center mt-[-8px]">&rsaquo;</span>

      <!-- Epic Code Gen with self-loop -->
      <div class="flex flex-col items-center">
        <div class="border-2 border-rose-700/60 bg-rose-900/20 rounded-xl p-4 flex flex-col gap-2">
          <p class="font-bold text-rose-300 text-sm text-center mb-1">Epic Code Gen</p>
          <div class="arch-node bg-rose-900/40 border border-rose-700/60 rounded-lg px-3 py-1.5 text-center">
            <p class="font-medium text-rose-300 text-xs">Code Generation</p>
          </div>
          <div class="arch-node bg-emerald-900/40 border border-emerald-700/60 rounded-lg px-3 py-1.5 text-center">
            <p class="font-medium text-emerald-300 text-xs">Component Onboarding</p>
          </div>
          <div class="arch-node bg-emerald-900/40 border border-emerald-700/60 rounded-lg px-3 py-1.5 text-center">
            <p class="font-medium text-emerald-300 text-xs">Docs</p>
          </div>
        </div>
        <div class="flex justify-center mt-1">
          <span class="text-[10px] font-semibold text-rose-400">Agent Loop</span>
        </div>
      </div>

      <span class="pipeline-arrow self-center mt-[-8px]">&rsaquo;</span>

      <!-- Build & Release + Bug Autofix stacked -->
      <div class="flex flex-col gap-3 self-center">
        <div class="arch-node bg-blue-900/40 border border-blue-700/60 rounded-lg px-4 py-3 text-center">
          <p class="font-semibold text-blue-300 text-sm">Build &amp; Release</p>
        </div>
        <div class="arch-node bg-emerald-900/40 border border-emerald-700/60 rounded-lg px-4 py-3 text-center">
          <p class="font-semibold text-emerald-300 text-sm">Bug Autofix</p>
        </div>
      </div>
    </div>

    <!-- Legend -->
    <div class="flex items-center gap-6 mt-6 pt-4 border-t border-slate-800 justify-center">
      <div class="flex items-center gap-2">
        <span class="w-2.5 h-2.5 rounded-full bg-emerald-500"></span>
        <span class="text-xs text-slate-400">In production</span>
      </div>
      <div class="flex items-center gap-2">
        <span class="w-2.5 h-2.5 rounded-full bg-amber-500"></span>
        <span class="text-xs text-slate-400">In testing</span>
      </div>
      <div class="flex items-center gap-2">
        <span class="w-2.5 h-2.5 rounded-full bg-blue-500"></span>
        <span class="text-xs text-slate-400">Planned</span>
      </div>
      <div class="flex items-center gap-2">
        <span class="w-2.5 h-2.5 rounded-full bg-rose-500"></span>
        <span class="text-xs text-slate-400">In development</span>
      </div>
    </div>
  </div>
</section>

<!-- ═══════════════ KANBAN STORY BOARD ═══════════════ -->
<section class="max-w-7xl mx-auto px-6 py-4">
  <h2 class="text-lg font-semibold text-slate-300 mb-2 flex items-center gap-2">
    <svg class="w-5 h-5 text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6"/>
    </svg>
    Agentic SDLC Pipeline Journey &mdash; {escape(strat_key)}
  </h2>
  <p class="text-slate-500 text-sm mb-6">Click a stage to see its artifacts</p>

  <!-- Kanban Cards -->
  <div class="grid grid-cols-5 gap-3 mb-8">

    <div class="stage-card bg-slate-900 border-2 border-slate-700 rounded-xl p-4 text-center" onclick="toggleStage('rfe')" id="card-rfe">
      <div class="w-10 h-10 mx-auto mb-3 rounded-full bg-emerald-900/50 flex items-center justify-center">
        <svg class="w-5 h-5 text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
        </svg>
      </div>
      <h3 class="font-semibold text-sm text-white mb-1">RFE</h3>
      <p class="text-xs text-slate-500">Customer Request</p>
    </div>

    <div class="stage-card bg-slate-900 border-2 border-slate-700 rounded-xl p-4 text-center" onclick="toggleStage('strategy')" id="card-strategy">
      <div class="w-10 h-10 mx-auto mb-3 rounded-full bg-blue-900/50 flex items-center justify-center">
        <svg class="w-5 h-5 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/>
        </svg>
      </div>
      <h3 class="font-semibold text-sm text-white mb-1">Strategy</h3>
      <p class="text-xs text-slate-500">AI Analysis</p>
    </div>

    <div class="stage-card bg-slate-900 border-2 border-slate-700 rounded-xl p-4 text-center" onclick="toggleStage('epics')" id="card-epics">
      <div class="w-10 h-10 mx-auto mb-3 rounded-full bg-purple-900/50 flex items-center justify-center">
        <svg class="w-5 h-5 text-purple-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z"/>
        </svg>
      </div>
      <h3 class="font-semibold text-sm text-white mb-1">Epic Breakdown</h3>
      <p class="text-xs text-slate-500">Decomposition</p>
    </div>

    <div class="stage-card bg-slate-900 border-2 border-slate-700 rounded-xl p-4 text-center" onclick="toggleStage('agentloop')" id="card-agentloop">
      <div class="w-10 h-10 mx-auto mb-3 rounded-full bg-amber-900/50 flex items-center justify-center">
        <svg class="w-5 h-5 text-amber-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/>
        </svg>
      </div>
      <h3 class="font-semibold text-sm text-white mb-1">Agent Loop</h3>
      <p class="text-xs text-slate-500">Epic Code Gen</p>
    </div>

    <div class="stage-card bg-slate-900 border-2 border-slate-700 rounded-xl p-4 text-center" onclick="toggleStage('done')" id="card-done">
      <div class="w-10 h-10 mx-auto mb-3 rounded-full bg-emerald-900/50 flex items-center justify-center">
        <svg class="w-5 h-5 text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
        </svg>
      </div>
      <h3 class="font-semibold text-sm text-white mb-1">Done</h3>
      <p class="text-xs text-slate-500">PR &amp; Next Steps</p>
    </div>

  </div>

  <!-- ═══════════════ DETAIL PANELS ═══════════════ -->

  <!-- RFE Panel -->
  <div id="panel-rfe" class="detail-panel mb-4">
    <div class="bg-slate-900 border border-slate-800 rounded-xl p-6">
      <div class="flex items-center gap-3 mb-4">
        <span class="px-2.5 py-1 rounded-md bg-emerald-500/20 text-emerald-400 text-xs font-semibold uppercase">Stage 1</span>
        <h3 class="text-xl font-bold text-white">Request for Enhancement</h3>
      </div>
      <p class="text-slate-400 mb-4"><span class="text-white font-semibold">The What</span> — A customer or product manager submits a feature request. This is where the pipeline begins.</p>

      <div class="mb-4">
        <a href="https://redhat.atlassian.net/browse/RHAIRFE-2224" target="_blank"
           class="text-blue-400 hover:text-blue-300 font-mono font-semibold text-lg">RHAIRFE-2224</a>
        <span class="text-slate-300 text-lg ml-2">{escape(title)}</span>
      </div>

      <div class="bg-slate-800/50 border border-emerald-700/30 rounded-lg p-4 mb-6">
        <div class="flex items-center gap-2 mb-2">
          <h4 class="text-sm font-semibold text-emerald-400">Summary</h4>
        </div>
        <p class="text-slate-300 text-sm leading-relaxed">{md_inline_to_html(rfe_summary)}</p>
      </div>

      <details class="group">
        <summary class="cursor-pointer text-sm font-semibold text-slate-400 hover:text-slate-200 flex items-center gap-2">
          <svg class="w-4 h-4 transition-transform group-open:rotate-90" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
          Full RFE Details
        </summary>
        <div class="mt-3 ml-2">
          {rfe_tree_html}
        </div>
      </details>
    </div>
  </div>

  <!-- Strategy Panel -->
  <div id="panel-strategy" class="detail-panel mb-4">
    <div class="bg-slate-900 border border-slate-800 rounded-xl p-6">
      <div class="flex items-center gap-3 mb-4">
        <span class="px-2.5 py-1 rounded-md bg-blue-500/20 text-blue-400 text-xs font-semibold uppercase">Stage 2</span>
        <h3 class="text-xl font-bold text-white">AI-Generated Strategy</h3>
      </div>
      <p class="text-slate-400 mb-4"><span class="text-white font-semibold">The How</span> — AI analyzes the RFE, researches the codebase, consults architecture docs, and produces a comprehensive technical strategy.</p>

      <div class="mb-4">
        <a href="https://redhat.atlassian.net/browse/{escape(strat_key)}" target="_blank"
           class="text-blue-400 hover:text-blue-300 font-mono font-semibold text-lg">{escape(strat_key)}</a>
        <span class="text-slate-300 text-lg ml-2">{escape(title)}</span>
      </div>

      <div class="bg-slate-800/50 border border-blue-700/30 rounded-lg p-4 mb-6">
        <div class="flex items-center gap-2 mb-2">
          <h4 class="text-sm font-semibold text-blue-400">TL;DR</h4>
          <span class="px-2 py-0.5 rounded-full bg-blue-500/20 text-blue-400 text-[10px] font-semibold uppercase tracking-wider">AI Generated</span>
        </div>
        <p class="text-slate-300 text-sm leading-relaxed">{md_inline_to_html(tldr)}</p>
      </div>

      <details class="mb-6 group">
        <summary class="cursor-pointer text-sm font-semibold text-slate-400 hover:text-slate-200 flex items-center gap-2">
          <svg class="w-4 h-4 transition-transform group-open:rotate-90" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
          Full AI-Generated Strategy
        </summary>
        <div class="mt-3 ml-2">
          {strat_tree_html}
        </div>
      </details>

      <div class="bg-slate-800/50 border border-emerald-700/30 rounded-lg p-4">
        <div class="flex items-center gap-2 mb-3">
          <svg class="w-5 h-5 text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
          </svg>
          <h4 class="text-sm font-semibold text-emerald-400 uppercase tracking-wider">Staff Engineer Review &amp; Sign-off</h4>
          <span class="px-2 py-0.5 rounded-full bg-emerald-500/20 text-emerald-400 text-[10px] font-semibold uppercase tracking-wider">Human validated the AI generation</span>
        </div>
        <div class="flex flex-wrap gap-2 mb-3">
          {staff_engineer_tags}
        </div>
        <details class="group">
          <summary class="cursor-pointer text-xs text-slate-500 hover:text-slate-300 flex items-center gap-1">
            <svg class="w-3 h-3 transition-transform group-open:rotate-90" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
            View full review
          </summary>
          <div class="mt-3 text-slate-300 text-sm leading-relaxed prose prose-invert prose-sm max-w-none border-t border-slate-700/50 pt-3">{md_to_html(staff_engineer)}</div>
        </details>
      </div>
    </div>
  </div>

  <!-- Epic Breakdown Panel -->
  <div id="panel-epics" class="detail-panel mb-4">
    <div class="bg-slate-900 border border-slate-800 rounded-xl p-6">
      <div class="flex items-center gap-3 mb-4">
        <span class="px-2.5 py-1 rounded-md bg-purple-500/20 text-purple-400 text-xs font-semibold uppercase">Stage 3</span>
        <h3 class="text-xl font-bold text-white">Epic Decomposition</h3>
      </div>
      <p class="text-slate-400 mb-4">AI breaks the strategy into ordered engineering tasks (epics) with a dependency graph. Tasks are processed in topological order &mdash; blocked work waits for upstream. When a strategy requires investigation before epic breakdown, the pipeline creates a <strong class="text-white">research spike</strong> to gather the needed context first.</p>

      <div class="grid md:grid-cols-2 gap-6">
        <div>
          <h4 class="text-sm font-semibold text-slate-300 mb-3 uppercase tracking-wider">Dependency Graph</h4>
          <div class="bg-slate-800/50 border border-slate-700/50 rounded-lg p-4">
            {dep_graph_dag}
          </div>
        </div>
        <div>
          <h4 class="text-sm font-semibold text-slate-300 mb-3 uppercase tracking-wider">Epics ({len(epics)} total)</h4>
          <div class="space-y-3">
            {epic_cards_html}
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Agent Loop Panel -->
  <div id="panel-agentloop" class="detail-panel mb-4">
    <div class="bg-slate-900 border border-slate-800 rounded-xl p-6">
      <div class="flex items-center gap-3 mb-4">
        <span class="px-2.5 py-1 rounded-md bg-amber-500/20 text-amber-400 text-xs font-semibold uppercase">Stage 4</span>
        <h3 class="text-xl font-bold text-white">Agent Loop</h3>
        <span class="text-sm text-slate-500">&mdash; Epic Code Gen</span>
      </div>
      <p class="text-slate-400 mb-6">
        The agent picks the next eligible epic from the queue and enters a <strong class="text-white">loop</strong>:
        generate code &rarr; self-review &rarr; open PR &rarr; human/agent review &rarr; fix &rarr; repeat until approved &rarr; merge &rarr; <strong class="text-white">next epic</strong>.
      </p>

      <!-- ── Epic Queue ── -->
      <div class="mb-8">
        <h4 class="text-sm font-semibold text-slate-300 mb-3 uppercase tracking-wider flex items-center gap-2">
          <svg class="w-4 h-4 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"/>
          </svg>
          Epic Queue ({len(epics)} epics)
        </h4>
        <div class="pb-2">
          {dep_graph_dag}
        </div>
      </div>

      <!-- ── The Loop Diagram ── -->
      <div class="mb-8">
        <h4 class="text-sm font-semibold text-slate-300 mb-4 uppercase tracking-wider flex items-center gap-2">
          <svg class="w-4 h-4 text-amber-400 loop-arrow" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/>
          </svg>
          The Loop
        </h4>

        <!-- Loop flow visualization -->
        <div class="flex items-start gap-4">

          <!-- Box 1: Generation -->
          <div class="flex-1 bg-slate-800/30 border border-slate-700/50 rounded-xl p-4">
            <p class="text-[10px] font-semibold text-slate-500 uppercase tracking-wider mb-3">Generation <span class="text-slate-600">(Inner Loop)</span></p>
            <div class="flex items-center gap-2 flex-wrap justify-center">
              <div class="shrink-0 bg-blue-900/30 border border-blue-700/50 rounded-lg px-3 py-2 text-center">
                <p class="text-xs font-semibold text-blue-400">Spec</p>
              </div>
              <svg class="w-4 h-4 text-slate-600 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
              <div class="shrink-0 bg-emerald-900/30 border border-emerald-700/50 rounded-lg px-3 py-2 text-center">
                <p class="text-xs font-semibold text-emerald-400">Code</p>
              </div>
              <svg class="w-4 h-4 text-slate-600 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
              <div class="shrink-0 bg-purple-900/30 border border-purple-700/50 rounded-lg px-3 py-2 text-center">
                <p class="text-xs font-semibold text-purple-400">N Review</p>
              </div>
              <svg class="w-4 h-4 text-slate-600 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
              <div class="shrink-0 bg-amber-900/30 border border-amber-700/50 rounded-lg px-3 py-2 text-center">
                <p class="text-xs font-semibold text-amber-400">Score</p>
              </div>
              <svg class="w-4 h-4 text-slate-600 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
              <div class="shrink-0 bg-emerald-900/30 border border-emerald-700/50 rounded-lg px-3 py-2 text-center">
                <p class="text-xs font-semibold text-emerald-400">PR</p>
              </div>
            </div>
            <div class="flex justify-center mt-3">
              <div class="flex items-center gap-1.5 text-red-400">
                <svg class="w-4 h-4 loop-arrow" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6"/>
                </svg>
                <span class="text-[11px] font-semibold">Score &lt; 8.0 &rarr; iterate</span>
              </div>
            </div>
          </div>

          <svg class="w-6 h-6 text-slate-600 shrink-0 self-center" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>

          <!-- Box 2: Review Loop -->
          <div class="flex-1 bg-slate-800/30 border border-amber-700/30 rounded-xl p-4">
            <p class="text-[10px] font-semibold text-slate-500 uppercase tracking-wider mb-3">Review Loop <span class="text-slate-600">(Outer Loop)</span></p>
            <div class="flex items-center gap-2 flex-wrap justify-center">
              <div class="shrink-0 bg-blue-900/30 border border-blue-700/50 rounded-lg px-3 py-2 text-center">
                <p class="text-xs font-semibold text-blue-400">PR Review</p>
                <p class="text-[10px] text-slate-500">Human + Agent</p>
              </div>
              <svg class="w-4 h-4 text-slate-600 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
              <div class="shrink-0 bg-emerald-900/30 border border-emerald-700/50 rounded-lg px-3 py-2 text-center">
                <p class="text-xs font-semibold text-emerald-400">Code Fix</p>
              </div>
            </div>
            <div class="flex justify-center mt-3">
              <div class="flex items-center gap-1.5 text-amber-400">
                <svg class="w-4 h-4 loop-arrow" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6"/>
                </svg>
                <span class="text-[11px] font-semibold">Changes requested &rarr; fix &amp; push</span>
              </div>
            </div>
          </div>

          <svg class="w-6 h-6 text-slate-600 shrink-0 self-center" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>

          <!-- Box 3: Done -->
          <div class="shrink-0 flex flex-col items-center gap-2 self-center">
            <div class="bg-emerald-900/30 border border-emerald-700/50 rounded-lg px-3 py-2 text-center">
              <p class="text-xs font-semibold text-emerald-400">Merge PR</p>
            </div>
            <svg class="w-4 h-4 text-slate-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 14l-7 7-7-7"/></svg>
            <div class="bg-emerald-900/30 border border-emerald-700/50 rounded-lg px-3 py-2 text-center">
              <p class="text-xs font-semibold text-emerald-400">Close Epic</p>
            </div>
          </div>

        </div>
      </div>

      <!-- ── Pipeline Run Timeline ── -->
      <div>
        <h4 class="text-sm font-semibold text-slate-300 mb-4 uppercase tracking-wider flex items-center gap-2">
          <svg class="w-4 h-4 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/>
          </svg>
          Agentic Pipeline Loops
        </h4>

        <div class="space-y-3">
          {epic_timeline_blocks}
        </div>
      </div>

    </div>
  </div>

  <!-- Done Panel -->
  <div id="panel-done" class="detail-panel mb-4">
    <div class="bg-slate-900 border border-slate-800 rounded-xl p-6">
      <div class="flex items-center gap-3 mb-4">
        <span class="px-2.5 py-1 rounded-md bg-emerald-500/20 text-emerald-400 text-xs font-semibold uppercase">Stage 5</span>
        <h3 class="text-xl font-bold text-white">Result</h3>
      </div>

      <div class="grid md:grid-cols-3 gap-4 mb-6">
        <div class="bg-slate-800/50 border border-slate-700/50 rounded-lg p-4 text-center">
          <p class="text-3xl font-bold text-emerald-400">{len([e for e in epics if e.get('pr_url')])}</p>
          <p class="text-xs text-slate-500 uppercase tracking-wider mt-1">PRs Opened</p>
        </div>
        <div class="bg-slate-800/50 border border-slate-700/50 rounded-lg p-4 text-center">
          <p class="text-3xl font-bold text-amber-400">{len([e for e in epics if e.get('status') == 'Blocked'])}</p>
          <p class="text-xs text-slate-500 uppercase tracking-wider mt-1">Waiting on Dependencies</p>
        </div>
        <div class="bg-slate-800/50 border border-slate-700/50 rounded-lg p-4 text-center">
          <p class="text-3xl font-bold text-blue-400">{len(epics)}</p>
          <p class="text-xs text-slate-500 uppercase tracking-wider mt-1">Total Epics</p>
        </div>
      </div>

      <div class="bg-slate-800/30 border border-slate-700/50 rounded-lg p-4">
        <h4 class="text-sm font-semibold text-slate-300 mb-2">What Happens Next</h4>
        <ul class="space-y-2 text-sm text-slate-400">
          <li class="flex items-start gap-2">
            <svg class="w-4 h-4 text-emerald-400 mt-0.5 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4"/></svg>
            PR is reviewed and merged by human engineers
          </li>
          <li class="flex items-start gap-2">
            <svg class="w-4 h-4 text-blue-400 mt-0.5 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6"/></svg>
            Once merged, dependent epics automatically unblock and the pipeline processes them
          </li>
          <li class="flex items-start gap-2">
            <svg class="w-4 h-4 text-purple-400 mt-0.5 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/></svg>
            The pipeline converges over multiple runs until all epics have PRs
          </li>
        </ul>
      </div>
    </div>
  </div>

</section>

<!-- ═══════════════ FOOTER ═══════════════ -->
<footer class="max-w-7xl mx-auto px-6 py-8 border-t border-slate-800">
  <div class="flex items-center justify-between">
    <div class="flex items-center gap-3">
      <div class="w-6 h-6 bg-red-600 rounded-sm flex items-center justify-center">
        <svg viewBox="0 0 24 24" class="w-4 h-4 text-white" fill="currentColor">
          <path d="M12 2L2 7v10l10 5 10-5V7L12 2zm0 2.18L19.18 8 12 11.82 4.82 8 12 4.18z"/>
        </svg>
      </div>
      <span class="text-sm text-slate-500">Red Hat AI</span>
    </div>
    <span class="text-xs text-slate-600">Generated {escape(timestamp)}</span>
  </div>
</footer>

<script>
  let activeStage = null;

  function toggleStage(stage) {{
    const panel = document.getElementById('panel-' + stage);
    const card = document.getElementById('card-' + stage);

    if (activeStage === stage) {{
      panel.classList.remove('open');
      card.classList.remove('active');
      card.style.borderColor = '';
      card.style.boxShadow = '';
      activeStage = null;
      return;
    }}

    // Close any open panel
    if (activeStage) {{
      document.getElementById('panel-' + activeStage).classList.remove('open');
      const prevCard = document.getElementById('card-' + activeStage);
      prevCard.classList.remove('active');
      prevCard.style.borderColor = '';
      prevCard.style.boxShadow = '';
    }}

    panel.classList.add('open');
    card.classList.add('active');
    card.style.borderColor = '#3b82f6';
    card.style.boxShadow = '0 0 20px rgba(59, 130, 246, 0.2)';
    activeStage = stage;

    // Smooth scroll to panel
    setTimeout(() => {{
      panel.scrollIntoView({{ behavior: 'smooth', block: 'nearest' }});
    }}, 100);
  }}

  // Animate score bars on visibility
  const observer = new IntersectionObserver((entries) => {{
    entries.forEach(e => {{
      if (e.isIntersecting) {{
        e.target.querySelectorAll('.score-fill').forEach(bar => {{
          bar.classList.add('animated');
        }});
      }}
    }});
  }});
  document.querySelectorAll('.detail-panel').forEach(p => observer.observe(p));
</script>
</body>
</html>"""

    output_path = os.path.join(output_dir, f"{strat_key}-pipeline-story.html")
    with open(output_path, "w") as f:
        f.write(page_html)

    print(f"Generated: {output_path}")
    return output_path


def main():
    parser = argparse.ArgumentParser(description="Generate pipeline story HTML")
    parser.add_argument("strat_key", help="Strategy key (e.g., RHAISTRAT-1749)")
    parser.add_argument("--data-dir", required=True,
                        help="Path to pipeline data directory for this strategy")
    parser.add_argument("--output-dir", default="epic-reports",
                        help="Output directory for the HTML file")
    parser.add_argument("--screenshots-dir", default=None,
                        help="Directory containing screenshot images")
    args = parser.parse_args()

    generate_pipeline_story(args.strat_key, args.data_dir, args.output_dir,
                            args.screenshots_dir)


if __name__ == "__main__":
    main()
